### ISSUE TITLE
CI: codecov runs fail with 429 during upload

### ISSUE THREAD

**Issue by dvdplm** [entropyxyz/crypto-primes#44] opened 2024-09-14 18:41 UTC
There seems to be an issue with the codecov upload action in this repo. Possibly the GH Action is outdated or the `CODECOV_TOKEN` secret is wrong?

See [this](https://github.com/entropyxyz/crypto-primes/actions/runs/10861321391/job/30149576771?pr=43#step:6:34) for an example failure.

**Comment by fjarri** [comment] 2024-09-15 17:28
Possibly caused by an outdated codecov action version, I bumped it in #45, and the codecov action passed. Closing for now, reopen if it happens again.

**Closed by fjarri** 2024-09-15 17:28 UTC
Labels: team:system-reliability-engineers
